services:
  - docker
matrix:
  include:
  - language: go
    go:
    - 1.11.x
    before_script:
    - mv ../../XiaoMi ../../xiaomi
    - cd ../../xiaomi/naftis
    script:
    - make fmt lint vet build.api
  - language: node_js
    node_js:
    - 8
    script:
    - make build.ui
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fmRoV3kxw95zYyZSQuTiHHTQjEMikYXRae2qtuyLRw69yPpHmGilzUKr88KEkJvaq21p00g6GVZj9BdeJ0mJyOMhihgVjOrii+pSnPDWJX4Lj/gtu5BsKuHjHI+gtgDebyftcI+aXCJtvDzpRZVk3VsvmUQnwPapIcZ6NhCn0QJDGOy3klW/jjwkhto/8/FEgWy4ON1sL4TSzUa/67ZBHUBeYu7j0kETaKsJWu9GrPJf8sIFhpMscIy3J5dGvo7PK/DSC+YCkAFpiK57El1yaH5Kf8mn/WZlMvFSBF616Ru5Zsei+Oa9J3j+HYp4s2mCiWwh0RBnoBmyePYJ0CyERmj+dxORtHzVa+AVkJL1LokgmmBOFjmmz5/talswYqKUMbLztjN836wpoSnPZsGdfwVLjYj37iYEyth7i4G4rGv9sZKWoKxCdCzgeROQh11u1oexohw1SkRnXdNA9AF70IPtIlP3WpchokazZ5A0TI73UktOrCsfi6nFKgNS1NfM/7pGruKcmkTHJqM2FmBepaBEUDk4jIrf0oy5FmVESgirB0Tf3Lv9Lo9Z7brHjyoMFyiR+oCW218JIp1XDM9qCX81jBr14MXbpXaFjRKwgwBWxe1O4kVvx4vnhDZCGhYvZdy2f5nnEIyqCDba/kpjnm0q9cnmf97j8oUlYVEHgKI=
  script: make docker push release
  file:
  - logshare.linux.amd64
  on:
    tags: true