services:
- docker
matrix:
  include:
  - language: go
    go:
    - 1.11.x
    before_script:
    - mv ../../XiaoMi ../../xiaomi
    - cd ../../xiaomi/naftis
    script:
    - make fmt lint vet build.api
  - language: node_js
    node_js:
    - 8
    script:
    - make build.ui
deploy:
  provider: releases
  skip_cleanup: true
  script: make docker push release
  file:
  - logshare.linux.amd64
  on:
    tags: true
  user: sevennt
  password:
    secure: j7KtPU1Fes2GoBxYjPwpM+8jb9QFxkynvtsPhuk90twX3NhnjXuv+KqzvvTwmO5Ta+BqqN73pwAZLCn4HCmeIWP1AbiJ0r8D+Fb1Qu0ciPLvJe8OX37JHr05/1YlegoF172Cg1pZnfv4UhNvvFfBrRT5dHG1vuPBcwR0epEZ1/4Cq5Z58m3lGbBwUlRL7tre/VX/bzYMdJk0O/HlmeTHb5BpF2xYkjiHvuC9Ym3XAR1qSF8sSFPqnvzt5+DUBPSW02fIX9LXZybFlOi+AkU/DurprRlI7W8HZmTLt3Uc2PuMfv15dVlAvcj7PeXOEuG4ktkvH9lrzlfQytClA9AUUPh6EGhSdqnz9OiJ3itXeM0Tkq6sPkYRS7oROE5yJok8k/qSuXhev6va5TQwRSNG/JnbFiC2glWtqMpGoAztVKID/uc6mdIk+o42M040/TqlAbH/lD3LpUVKJZIg5QO/753DINzcu63+5IifhM/VD+gnXR26/x1LqxmJ0XtaDNVbRotVe9XXqbjuqRn26PIQqwmsWrW597rTbYrIVNMAsr0/0wMweLEDZ6hgpFAacw3SVIZHZ24try1zYEiaS6Pk96iHPGxUWUzUofVm4EKd/10z7XaRTae4NlukuCTvCLSypTXdiYZvGg5Y3lHrQodlon7c/gUVuzG/wQww51Eqb3w=
