services:
- docker
matrix:
  include:
  - language: go
    go:
    - 1.11.x
    before_script:
    - mv ../../XiaoMi ../../xiaomi
    - cd ../../xiaomi/naftis
    script:
    - make fmt lint vet build.api
  - language: node_js
    node_js:
    - 8
    script:
    - make build.ui
deploy:
  provider: releases
  skip_cleanup: true
  script: make docker push release
  file:
  - logshare.linux.amd64
  on:
    tags: true
  user: sevennt
  api_key:
    secure: eJR5T6t0UVG3rKiq41oRUaS+pYQfLNwjY8VLJZ+K3WrnJOyij1S9c4by7HhZYIFHFMbK9dmlExKkdAmSOCHNj/sJ9UMQ7DHRszDAGcMGYtx30RoQIBerBXOKt77x0YLK9JnYvY+Sfo6F6e5On2kQ51q1QsZ9NUDCgjcW4z+5PO2F3CUv4fevMjVe9OG29A4aNiKJX1xBveV4vqmjGVYJuGxMMggwGU61p3H5SZBtC7zIZf5M+HwPccDeYhQMzF7yMFYhI89w6zuNq9vwcHt6nwIcJ2JMabsRokWfft1HYAx7/rwMePG1AaBZa1UGBmHgEAXCKtfrhgSmlqCqiOqfkwktZP9jhmpASjs6dU+5DdgIc9KY7KMgwFH84O4QXcubZAnN0/NUeNuaLkSo77YWWIh2tqz1aifVx7Xq844e2zkPyooFo3wz7IstmuLh7AiSht6dyYF3yURlw8ccum282nRYyKJbqkfcVsErkKYSalYgIY6tbIKMjPvafIGxhE2wokN7zP+OMekQGNy2aTj4mu2dkD6PatG3oAS2ekFquw15mGcdBlp2NtoGtqH2pER1LYxpqQa9sUZnF3/8TqaDj1LngfR3rcdoUNOTziLnSp/eJq+xw7ez8LFBF0efC9iuJx8LkvZShzKZLSSre4S4ERHohjFGBxpi/TRXTnfuOts=
