apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: naftis-ui
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: naftis-ui
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  template:
    metadata:
      labels:
        app: naftis-ui
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["/etc/nginx/sbin/nginx","-s","quit"]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: naftis-api
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: naftis-api
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: naftis-api
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: naftis-api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          args:
            - --config=/etc/naftis/config/config.toml
            - --istioNamespace=istio-system
          ports:
            - containerPort: {{ .Values.api.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /api/probe/healthy
              port: {{ .Values.api.service.internalPort }}
            initialDelaySeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/probe/healthy
              port: {{ .Values.api.service.internalPort }}
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
          volumeMounts:
            - name: {{ .Release.Namespace }}-config
              mountPath: /etc/naftis/config
      volumes:
        - name: {{ .Release.Namespace }}-config
          configMap:
            name: {{ .Release.Namespace }}-config
            items:
              - key: config
                path:  config.toml
